version: '2.0'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    depends_on:
      - php
    links:
      - php:php
  php:
    image: bitnami/php-fpm
    container_name: php
    expose:
      - 9000
    volumes:
      - ./www:/www
    links:
      - elasticsearch:es
  elasticsearch:
    image: elasticsearch
    container_name: es
    expose:
      - 9200
    ports:
      - 9200:9200



